### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot format given Object as a Date

### ISSUE THREAD

**Issue by oierngalirn** [ewen0930/WebStorm-Chinese#1]
JetBrains WebStorm 9.0.2

Internal error. Please report to http://youtrack.jetbrains.com

java.lang.IllegalArgumentException: Cannot format given Object as a Date
    at java.text.DateFormat.format(DateFormat.java:301)
    at java.text.Format.format(Format.java:157)
    at java.text.MessageFormat.subformat(MessageFormat.java:1313)
    at java.text.MessageFormat.format(MessageFormat.java:860)
    at java.text.Format.format(Format.java:157)
    at java.text.MessageFormat.format(MessageFormat.java:836)
    at com.intellij.BundleBase.format(BundleBase.java:64)
    at com.intellij.BundleBase.messageOrDefault(BundleBase.java:58)
    at com.intellij.BundleBase.message(BundleBase.java:72)
    at com.intellij.CommonBundle.message(CommonBundle.java:64)
    at com.intellij.ide.IdeBundle.message(IdeBundle.java:34)
    at com.intellij.ide.a.v.getLicenseRestrictionsMessages(v.java:29)
    at com.intellij.ui.Splash.showLicenseeInfo(Splash.java:171)
    at com.intellij.ui.Splash$SplashImage.paintIcon(Splash.java:202)
    at javax.swing.plaf.basic.BasicLabelUI.paint(BasicLabelUI.java:167)
    at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
    at javax.swing.JComponent.paintComponent(JComponent.java:778)
    at com.intellij.ui.Splash$1.paintComponent(Splash.java:72)
    at javax.swing.JComponent.paint(JComponent.java:1054)
    at javax.swing.JComponent.paintChildren(JComponent.java:887)
    at javax.swing.JComponent.paint(JComponent.java:1063)
    at javax.swing.JComponent.paintChildren(JComponent.java:887)
    at javax.swing.JComponent.paint(JComponent.java:1063)
    at javax.swing.JLayeredPane.paint(JLayeredPane.java:585)
    at javax.swing.JComponent.paintChildren(JComponent.java:887)
    at javax.swing.JComponent.paintToOffscreen(JComponent.java:5226)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1529)
    at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1452)
    at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
    at javax.swing.JComponent.paint(JComponent.java:1040)
    at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
    at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
    at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
    at java.awt.Container.paint(Container.java:1967)
    at java.awt.Window.paint(Window.java:3877)
    at javax.swing.RepaintManager$3.run(RepaintManager.java:819)
    at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
    at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
    at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
    at java.awt.Dialog.show(Dialog.java:1082)
    at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:870)
    at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:667)
    at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:638)
    at com.intellij.idea.Main.showMessage(Main.java:238)
    at com.intellij.idea.Main.showMessage(Main.java:208)
    at com.intellij.ide.plugins.PluginManager.processException(PluginManager.java:129)
    at com.intellij.ide.plugins.PluginManager$3.uncaughtException(PluginManager.java:151)
    at java.awt.EventDispatchThread.processException(EventDispatchThread.java:264)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:256)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by oierngalirn** [comment]
9.0.2 updata
ActionsBundle.properties
CodeInsightBundle.properties
IdeBundle.properties
InspectionsBundle.properties
VcsBundle.properties

**Comment by ewen0930** [comment]
WebStorm 9.0.2 的 resources_en.jar 和以前版本有差异
